version: '3.9'

services:
  dev:
    container_name: react_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules # Avoids overwriting `node_modules`
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables file watching on some systems
      - WATCHPACK_POLLING=true
    command: npm start

  prod:
    container_name: react_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
